### ISSUE TITLE
Sending more than one variable with send_var() causes subsequent sync() call to block forever

### ISSUE THREAD

**Issue by TheHashTableSlasher** [CURENT/dime#14]
e.g. running
```
d = dime('matlab', 'ipc', '/tmp/dime.sock');
d.send_var('matlab', 'a');
d.send_var('matlab', 'b');
 ...
d.send_var('matlab', 'z');
d.sync();
```
works fine, but
```
d = dime('matlab', 'ipc', '/tmp/dime.sock');
d.send_var('matlab', 'a', 'b', ..., 'z');
d.sync();
```
Blocks forever on the last line. The server is receiving extra 'send' commands after 'sync' is called, so I suspect this is a client-side issue.

**Comment by cuihantao** [comment]
Does it work if you just send two at a time?

**Comment by TheHashTableSlasher** [comment]
Well, it _used_ to not for anything more than one. Now it doesn't have any issues about it? I can only guess one of the commits I made today fixed it incidentally. I'm going to close this for now, but I will reopen it if it arises again.
