### ISSUE TITLE
Add Python client

### ISSUE THREAD

**Issue by TheHashTableSlasher** [CURENT/dime#17]
Something like:
```
import dime
import numpy as np

d = dime.DimeClient("python", "ipc", "/tmp/dime.sock")

d["a"] = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d.send_var("python", "a")
del d["a"]
d.sync()

print(d["a"])
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
```

Note that #3 needs to be completed as a dependency. Also, the server should be aware of its clients' platforms, and instruct them to change their serialization method depending on what other types of clients are connected.

**Comment by JunejaAmmy** [comment]
Hi, 

I'm facing the below issue, could you please help?


![image](https://user-images.githubusercontent.com/97614806/156225373-1b5ff69e-e306-4a0b-9c55-afffeff08f72.png)
