### ISSUE TITLE
RuntimeError: Invalid DiME message

### ISSUE THREAD

**Issue by JunejaAmmy** [CURENT/dime#39]
Hi,

While trying to connect using tcp protocol, I'm facing below issue.

![image](https://user-images.githubusercontent.com/97614806/156225069-00b02515-b22c-447f-91a9-240b964d0748.png)

Any help will be appreciable.

Thanks,
Ammy

**Comment by TheHashTableSlasher** [comment]
What flags are you running the DiME server with?

**Comment by JunejaAmmy** [comment]
I didn't get you. Can you please elaborate about flags?

**Comment by TheHashTableSlasher** [comment]
Exactly what command did you type to initialize the DiME server?

**Comment by TheHashTableSlasher** [comment]
I'm in MK212 tuesdays and thursdays if you wanna just take your laptop down here and have me look at it

**Comment by JunejaAmmy** [comment]
The echo-server was not sending the **DiME** in the header. Now I have included it. And the error is resolved.

Thanks!
