### ISSUE TITLE
What kind of bindata is required for the sync_r method to receive from the server?

### ISSUE THREAD

**Issue by JunejaAmmy** [CURENT/dime#40]
Hi,

I'm using DimeClient with python.
What kind of **bindata** is required for the **sync_r** method to receive from the server?

Please help!

![image](https://user-images.githubusercontent.com/97614806/157312684-9f64c1c6-3a32-4713-9efb-71a71c1c1abf.png)

**Comment by TheHashTableSlasher** [comment]
A DiME message over the network has three parts:

- A header ("DiME" in ASCII, plus length of other parts as 32-bit ints)
- A JSON component
- A binary component

DiME currently tries to include as much data as possible in JSON, because JSON is fast and has good cross-language support. In fact, the server only parses the header and JSON part, storing (but not interpreting) the binary part as necessary. But the desire to send data like typed n-dimensional matrices (which don't translate nicely to JSON) means that `send`, `broadcast` and `sync` also include an arbitrary binary part that describes the variable being sent/received, which is encoded differently. The exact binary representation depends on which clients have connected (e.g. if only Python clients are used, then DiME uses pickle to encode/decode variables). Does that answer your question?

**Comment by JunejaAmmy** [comment]
In my case, I'm not sending any bindata from echo-server as response of **sync** command. So I'm getting error of empty bindata.
Please suggest, what should I do?

**Comment by TheHashTableSlasher** [comment]
What code are you running to communicate with the DiME server (both to send _and_ receive the message)?

**Comment by JunejaAmmy** [comment]
Calling the sync method as below:

`var_names = self.dimec.sync(-1)`


And this is the echo-server side:

```
import socket
import struct
import pickle
import json

HOST = "127.0.0.1"  
PORT = 65432  
xyz = None 

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    unpickleddata = None
    conn, addr = s.accept()
    with conn:
        print(f"Connected by {addr}")
        while True:
            data = conn.recv(32768)
            header = data[0:12]
            jsondata_len, bindata_len = struct.unpack("!II", header[4:])
            newlength = jsondata_len + 12
            bindata = data[newlength:]
            jsondata = data[12: jsondata_len+12]
            print('jsondata: '+ str(jsondata))
            print('jsondata length : '+ str(jsondata_len))

            if(bindata != b''):
                unpickledData = pickle.loads(bindata)
                print(unpickledData)
    
            if not data:
                break
            conn.sendall(data)


```
            
            `

**Comment by TheHashTableSlasher** [comment]
You need to perform the handshake with the DiME server first, before you start receiving any variables. See the `open()` function code. Also, the message received from the DiME server may not be directly sendable back to it.

**Comment by JunejaAmmy** [comment]
I'm doing the process in the following order:
1. Handshake / open() function
    response: 
![image](https://user-images.githubusercontent.com/97614806/157449395-13ea0e89-23b0-44fa-8bd7-09da0f293d53.png)


2. Join
    response: 
![image](https://user-images.githubusercontent.com/97614806/157449458-108ef0ea-b1ca-4ac8-be38-a237a1f99240.png)


3. Devices
    response: 
![image](https://user-images.githubusercontent.com/97614806/157449547-0575cae9-93ea-41d5-9e07-8eb228e28b03.png)


4. Broadcast
    response: 
![image](https://user-images.githubusercontent.com/97614806/157449833-ca633603-787e-4bf6-8103-b27cfe88a1c6.png)

![image](https://user-images.githubusercontent.com/97614806/157449995-2355efb7-36eb-40f4-97a4-07451ede2e65.png)


5. Devices
    response: 
![image](https://user-images.githubusercontent.com/97614806/157450325-109e2cb4-ddc3-42f8-9c39-d5c6eea63da3.png)


7. Sync
    response: 
![image](https://user-images.githubusercontent.com/97614806/157450503-64583c72-a0fe-416e-bb9f-4a9fac754c41.png)


    **here, I'm getting error of empty bindata.**

Is this process correct?

**Comment by TheHashTableSlasher** [comment]
I don't think so, `sync` should return a variable. Though, it is really unclear to me what you are trying to accomplish. Are you reimplementing the client/server? Please, if you have time, come to my office in MK212.

**Comment by JunejaAmmy** [comment]
Thanks for the reply.

I wish if I could come to your office. I'm from India.

I'm running the DimeClient from ANDES (a simulation tool).

There are two files, please have a look:
https://github.com/cuihantao/andes/blob/master/andes/io/streaming.py
https://github.com/cuihantao/andes/blob/master/andes/routines/tds.py

**streaming.py** is calling functions of **DimeClient**.
Functions of **streaming.py** file are being called by **tds.py**.

**Comment by TheHashTableSlasher** [comment]
We can set up a Zoom call with Dr. Li and Jinning, then. What is your e-mail?

**Comment by JunejaAmmy** [comment]
Sure, that's a good idea. Below is my email.
18AmrinderSingh@gmail.com

**Comment by JunejaAmmy** [comment]
any update?

Also can you please brief me what is the use/purpose of the below server folder?
https://github.com/TheHashTableSlasher/dime/tree/master/server

Are these files necessary to run to use DiME, if yes?
How can I run these files? Do they need any compiler?

**Comment by JunejaAmmy** [comment]
Any update?

**Comment by TheHashTableSlasher** [comment]
I am sorry for the lack of updates, right now I am mostly preoccupied with completing my project defense. There's something wrong with the way you're connecting to the DiME server or setting it up. The server _never_ sends that kind of message back to the client upon `sync_r`.

If you're using Python, there's hardly any reason to jerry-rig a client yourself. I cannot replicate the error you're getting when I use the Python client included in the repo.
