### ISSUE TITLE
Facing issues while running Makefile

### ISSUE THREAD

**Issue by TheASingh** [CURENT/dime#42]
Hi Good Morning,

Can anyone please help me in running Makefile. I'm facing following issue. 

![image](https://user-images.githubusercontent.com/96423656/164032959-6de77d05-df45-42ab-b4f4-a07e69cc3ac2.png)

As mentioned in the comment, I uncommented the following lines:
![image](https://user-images.githubusercontent.com/96423656/164033708-58315e40-8df3-4a05-938c-7e7573386110.png)

I'm using mingw compiler on my system.

Your help will be appreciable.

Thanks.

**Comment by TheHashTableSlasher** [comment]
Make is saying it can't find MinGW. You need to change the line `CC := x86_64-w64-mingw32-gcc` to whatever your MinGW executable is called.

**Comment by TheASingh** [comment]
Thanks for the reply. I was able to fix this by changing the line to `CC := gcc`

As the server code has the following compile-time dependencies:
[Jansson](https://digip.org/jansson/)
[OpenSSL](https://www.openssl.org/)
[zlib](http://zlib.net/)

I downloaded them. Even after downloading, I'm getting below error:

![image](https://user-images.githubusercontent.com/96423656/164063950-ccb29261-4b3d-49dc-b153-956ab2bf91c2.png)

**At what location do I need to put these dependencies on my system to resolve this error?**
Currently, Jansson is installed at:
C:\Users\Dell\jansson-master

And Dime is installed at:
C:\Users\Dell\dime-master\server

**Comment by TheHashTableSlasher** [comment]
You need to install Jansson too, in a place where the headers and libs can be included. If you're using cygwin, just follow the instructions for a Unix install.

On April 19, 2022 1:47:44 PM EDT, RajanSingh ***@***.***> wrote:
>Thanks for the reply. I was able to fix this by changing the line to
>`CC := gcc`
>
>As the server code has the following compile-time dependencies:
>[Jansson](https://digip.org/jansson/)
>[OpenSSL](https://www.openssl.org/)
>[zlib](http://zlib.net/)
>
>I downloaded them. Even after downloading, I'm getting below error:
>
>![image](https://user-images.githubusercontent.com/96423656/164063950-ccb29261-4b3d-49dc-b153-956ab2bf91c2.png)
>
>**At what location do I need to put these dependencies on my system to
>resolve this error?**
>Currently, Jansson is installed at:
>C:\Users\Dell\jansson-master
>
>And Dime is installed at:
>C:\Users\Dell\dime-master\server
>
>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/TheHashTableSlasher/dime/issues/42#issuecomment-1102923213
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with monocles mail. Please excuse my brevity.
